### ISSUE TITLE
Running in lambda

### ISSUE THREAD

**Issue by stein-f** [Amatsagu/Tempest#15]
Hi, I might have missed it but is there a way to get this to run in lambda and API Gateway (HTTP API)?

I am using an adapter to run ListenAndServe in lambda which is working.

https://github.com/a-h/awsapigatewayv2handler

But I don't see a way to get a handle on the http.Handler - it's not exposed from within Tempest. If you could expose `client.handleRequest` it'd work.

I created a modified version which is working great, but would rather depend on this package.

```go
func (client *Client) LambdaStart() {
	client.running = true
	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		client.handleRequest(w, r)
	})
	awsapigatewayv2handler.ListenAndServe(handler) // from a-h/awsapigatewayv2handler
}
```

This way I can run Tempest in a serverless environment and use sns/sqs for messaging discord asynchronously.

**Comment by Amatsagu** [comment]
Hey @stein-f!
You've brought interesting case. I've never thought anyone would try and use Tempest in "serverless" architecture.

Feel free to open new pull request to implement it. I usually try to keep everything private unless it's required - that's why http client is hidden in current version. I assume it'll be enough to just expose pointer to http client inside Client struct?

**Comment by Amatsagu** [comment]
I've decided to make it in non invasive way by just adding simple hijack method. This should allow you to use Tempest with your custom lambda handler without issues. I will eventually add it to the next release but for now, feel free to use go get: https://github.com/Amatsagu/Tempest/tree/e41f893c0f02fadbdaa87c99635e73c21b736331

**Comment by stein-f** [comment]
Thanks @Amatsagu ! Appreciate the quick response and update. Feel free to close
