### ISSUE TITLE
TLS Support?

### ISSUE THREAD

**Issue by mopeyhat** [Amatsagu/Tempest#2]
I'm trying out using this library for my app, but found that Discord requires TLS for me to even put the webhook URL in the bot config. I had to swap over the `http.ListenAndServe` to `http.ListenAndServeTLS`; were you using some workaround or am I missing something else?

**Comment by Amatsagu** [comment]
Hey,
Yeah that might be a problem. The way I or I assume most people operate is that we use extra service like CloudFlare as a bridge:
![image](https://user-images.githubusercontent.com/81469656/213708695-d8b037c1-0ba7-4d53-bb24-25124fc82070.png)

So, your service(s) connects with CloudFlare DNS that is not only more efficient than those of namecheap or godaddy (from popular domain hosts) but also provide you with a bunch of tools for anty DDoS, caching, etc. Like on image higher, you have SSL certificate working only between client (discord in this case) and DNS (cloudflare). This solution is not perfect but it's already very secure since only way to find your service is by directly attacking ip and port which is hard in itself (assuming you won't leak it). It doesn't have to be CloudFlare, any tunnel will work and big apps with balance loader commonly uses tunnels anyway.

Yet I see issue you have. I don't have much of free time for now so feel free to open pull request with option to pick between normal and TLS listener.

**Comment by Amatsagu** [comment]
Honestly using tunnel/special DNS provides huge security gain and like maybe 1-2ms higher latency so it's always worth to use them, especially that most of CloudFlare tools are free.

**Comment by mopeyhat** [comment]
Ahh thanks for the clean explanation! I am very new to running my own web service, only done backend work. I will see about cleaning things up for a PR when I can.
