### ISSUE TITLE
RegisterCommand() sends application="0" 

### ISSUE THREAD

**Issue by nicocesar** [amatsagu/tempest#26]
RegisterCommand() needs something like:
```
	if command.ApplicationID == 0 {
		command.ApplicationID = client.ApplicationID
	}
```

To send the correct ApplicationID when registering the commands

**Comment by amatsagu** [comment]
Hi, I have nothing against adding that but could You tell me why you think it's needed? I'm using this library for few discord app projects that uses slash commands, user commands and message commands and never noticed any of them not working or being bugged. Field `ApplicationID` is here because it's part of Discord API, it will be returned to you if you requests from API all slash commands but as far as I know that's not required (and never was) when registering new commands.

**Comment by amatsagu** [comment]
I don't really have a reason not to add this so here you go, check out [0b7375d](https://github.com/amatsagu/tempest/commit/0b7375de6138a2d4170c7f6b68784e3931851ed5) commit. I'm still curious why You think it should be done this way.

**Comment by nicocesar** [comment]
fair question, I'm trying to track down a problem. For some reason nothing is failing when I start the example-bot but the interaction endpoint  doesn't get any calls and the slash commands aren't listed in the server. 

I'm using Cloud Run from GCP and trying to see if the problem is because something isn't registered properly or some other problem I have.

**Comment by amatsagu** [comment]
Hmm.. I'm not sure how Your testing environment looks like. Good start would be cloning example bot code from `master` branch and running it. Then you'll need some tool for exposing Application to the outside world so Discord API can detect it. I personally use [ngrok tunnels](https://ngrok.com/) because they're fast and free so works ideally for quick testing. However anything would work, cloudflare tunnels, etc. will work just fine.

I'm not sure if you know that or not, after starting Application - You need to give your API uri to discord so they know where to send all the data. **It requires https protocol.**
![image](https://github.com/amatsagu/tempest/assets/81469656/0caaad12-c016-4be5-80b5-c4feb6b568b1)

**Comment by amatsagu** [comment]
Oh right, how you invited bot?

Bots to use interactions properly require extra flag, use this invite link:
https://discord.com/oauth2/authorize?client_id=[YOUR_BOT_USER_ID]&permissions=0&scope=bot+applications.commands

If you happened to invite bot to your testing server without application.commands flag, it will be unable to register slash commands or receive them from this server. This could also be verified if you add error handler when registering commands. Just in case I would kick bot and invite them back using higher invite link.

**Comment by nicocesar** [comment]
Yeah most of my setup was ok, and good news: I made it to work with CloudRun! ... the problem was the starting point was the example on master where go.mod has 

`require github.com/Amatsagu/Tempest v1.1.7-0.20240310145558-c48446d33797`

I changed it to 1.2.0 and did the corresponding changes.

**Comment by nicocesar** [comment]
This issue can be closed!
